services:
  - type: web
    name: plux-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: YT_COOKIES
        sync: false
      - key: FRONTEND_URL
        sync: false
